<?php

$allSettings = $this->get_feed_settings();

foreach ($allSettings['ios']['Image'] as $key => $value) {
	$gui[$key] = $value['Standard'];
	$guiFile[$key] = '<input type="file" name="'.$key.'" />';
}

foreach ($allSettings['ios']['Language'] as $key => $value) {
	if(!isset($value['userValue'])) $value['userValue'] = '';
	$value['Standard'] = str_replace('\n', "\n", $value['Standard']);
	$guiInput[$key] = '<input type="text" value="'.$value['userValue'].'" placeholder="'.$value['Standard'].'" name="'.$key.'" />';
	$guiTextarea[$key] = '<textarea placeholder="'.$value['Standard'].'" name="'.$key.'">'.$value['userValue'].'</textarea>';
}

?>

<h1>iOS</h1>
<form id=feed_iphone action=admin-post.php method=post class=clearfix>
	<div class=feed_phone>
		<div class=feed_screen>
			<div class=feed_page_apps>
				<img data-name=app_icon src=<?php echo $gui['app_icon'] ?>>
				<p data-name=app_name></p>
			</div>
				
			<div class=feed_page_home>
				<img data-name=header_image src=<?php echo $gui['header_image']?> width=100%>
				<ul class=data>
					<li>
						<p data-name=description></p>
					</li>
				</ul>
				<a class=read_button data-name=start_reading></a>
			</div>
									
			<div class=feed_page_article>
				<img data-name=header_image src=<?php echo $gui['header_image']?> width=100%>
				<ul class="data feed_list">
					<li class=feed_read>
						<img data-name=read_icon src=<?php echo $gui['read_icon']?> width=22 height=22>
						<a>description</a>
					</li>
					<li class=feed_read>
						<img data-name=read_icon src=<?php echo $gui['read_icon']?> width=22 height=22>
						<a>description</a>
					</li>
					<li>
						<img data-name=unread_icon src=<?php echo $gui['unread_icon']?> width=22 height=22>
						<a>description</a>
					</li>
					<li class=feed_read>
						<img data-name=read_icon src=<?php echo $gui['read_icon']?> width=22 height=22>
						<a>description</a>
					</li>
					<li>
						<img data-name=unread_icon src=<?php echo $gui['unread_icon']?> width=22 height=22>
						<a>description</a>
					</li>
					<li>
						<img data-name=unread_icon src=<?php echo $gui['unread_icon']?> width=22 height=22>
						<a>description</a>
					</li>
				</ul>
			</div>

			<div class=feed_page_about>
				<div class=feed_header>
					<h1 data-name=about_header></h1>
					<a data-name=back></a>
				</div>
										
				<ul class=data>
					<li>
						<h3 data-name=about_title></h3>
						<p data-name=about_text></p>
						<p>This app was generated by http://feed.nu</p>
					</li>
				</ul>
										
			</div>

			<div class=feed_page_setting>
				<div class=feed_header>
					<h1 data-name=setting_header></h1>
					<a data-name=back></a>
				</div>
										
				<ul class="data feed_list">
					<li class="feed_onoff">
						<a data-name=hide_read></a>
					</li>
					<li>
						<a data-name=clear_db></a>
					</li>
					<li>
						<a data-name=reset_app></a>
					</li>
				</ul>
										
			</div>

			<div class=feed_page_confirm>
				<div class=feed_header>
					<h1 data-name=settings_title></h1>
					<a data-name=back></a>
				</div>
										
				<ul class="data feed_list">
					<li class=feed_onoff>
						<a data-name=hide_read></a>
					</li>
					<li>
						<a data-name=clear_db></a>
					</li>
					<li>
						<a data-name=reset_app></a>
					</li>
				</ul>
				<div class=feed_confirm>
					<h4 data-name=confirm_title style="color: rgb(255, 255, 255); text-align: center; margin: 0pt; font: bold 14px/44px Helvetica;"></h4>
					<p  data-name=sure_text style="text-align: center; position: relative; top: -20px;"></p>
					<p  data-name=yes style="top: 63px; text-align: center; width: 105px; left: 8px; font-weight: bold;"></p>
					<p  data-name=no style="top: 63px; text-align: center; width: 105px; left: 115px; font-weight: bold;"></p>
				</div>
			</div>
									
			<div class=feed_dock>
				<p data-name=dock_home></p>
				<p data-name=dock_article style="left: 64px;"></p>
				<p data-name=dock_about style="left: 126px;"></p>
				<p data-name=dock_setting style="left: 189px;"></p>
			</div>
									
									
		</div>
	</div>
							
	<div class="feed_tools">
		<?php
			echo
				$this->add_div('apps', 'App icon', $guiFile['app_icon']),
				$this->add_div('apps', 'App name:', $guiInput['app_name']),
				$this->add_div('home', 'Top image:', $guiFile['header_image']), 
				$this->add_div('home', 'Description:', $guiTextarea['description']),
				$this->add_div('home', 'Start reading:', $guiInput['start_reading']),
				$this->add_div('home', 'Home:', $guiInput['dock_home']),
				$this->add_div('home', 'Article:', $guiInput['dock_article']),
				$this->add_div('home', 'About:', $guiInput['dock_about']),
				$this->add_div('home', 'Settings:', $guiInput['dock_setting']),
				$this->add_div('article', 'Unread icon:', $guiFile['unread_icon']),
				$this->add_div('article', 'Read icon:', $guiFile['read_icon']),
				$this->add_div('about', 'About header:', $guiInput['back']),
				$this->add_div('about', 'About header:', $guiInput['about_header']),
				$this->add_div('about', 'About title:', $guiInput['about_title']),
				$this->add_div('about', 'Text:', $guiTextarea['about_text']),
				$this->add_div('setting', 'Setting Header:', $guiInput['setting_header']),
				$this->add_div('setting', 'Hide read item:', $guiInput['hide_read']),
				$this->add_div('setting', 'Clear posts:', $guiInput['clear_db']),
				$this->add_div('setting', 'Reset app:', $guiInput['reset_app']),
				$this->add_div('confirm', 'comfirm:', $guiInput['confirm_title']),
				$this->add_div('confirm', 'are you sure:', $guiInput['sure_text']),
				$this->add_div('confirm', 'Yes:', $guiInput['yes']),
				$this->add_div('confirm', 'No:', $guiInput['no']);
		?>							
		<div class="feed_nav">
			<button class="button feed_prev alignleft" style="border-bottom-right-radius: 0; border-top-right-radius: 0; padding: 0 0 4px;" disabled>Prev</button>
			<button class="button feed_next alignleft" style="border-bottom-left-radius: 0; border-top-left-radius: 0; padding: 0 0 4px;">Next</button>
			<input type=hidden value=feed_cmd name=action>
			<input type=hidden value=saveIosGui name=cmd>
			<input type=submit value=Save class=button-primary style="float:right">
		</div>
								
	</div>
</form>